### ISSUE TITLE
Error: Unexpected JSON in toke position 0 when using magic link

### ISSUE THREAD

**Issue by bdougie** [stytchauth/stytch-nextjs-integration#55]
When trying the live version o this template I get the following error. My assumption is that it does not parse the email input but I did not dig further than look at this line: https://github.com/stytchauth/stytch-nextjs-integration/blob/main/lib/emlUtils.ts#L5. 

I thought it was due to tokens not being set but when deployed to Vercel, it also fails there. 

![Screen Shot 2022-03-22 at 9 39 41 AM](https://user-images.githubusercontent.com/5713670/159530495-feda9183-0ad9-440a-a203-775112c1dc5a.png)

**Comment by cal-stytch** [comment]
Hi @bdougie, to confirm this is failing both locally and on Vercel? Have you gotten this template to work under any circumstances thus far, or have all configurations failed?

**Comment by bdougie** [comment]
I can confirm that OAuth with GitHub works.

**Comment by cal-stytch** [comment]
Awesome! To confirm this issue is now resolved?

**Comment by bdougie** [comment]
Yes, this is resolved
